import Enum from './base.js';

export default new Enum([
    {key: 'OBJECT', value: 'Объект'},
    {key: 'BUILDING', value: 'Строение'},
    {key: 'CASTLE', value: 'Замок'},
    {key: 'CHURCH', value: 'Кирха'},
    {key: 'COMPLEX', value: 'Комплекс зданий'},
    {key: 'CEMETERY', value: 'Захоронение'},
    {key: 'CUSSR', value: 'Советские воины'},
    {key: 'CDEU', value: 'Немецкие воины'},
    {key: 'CRUS', value: 'Воины Российской Империи'},
    {key: 'MEMORIAL', value: 'Мемориал'},
    {key: 'ANCIENT', value: 'Античный объект'},
    {key: 'WTOWER', value: 'Башня водонапорная'},
    {key: 'AREA', value: 'Территория'},
    {key: 'HOUSE', value: 'Дом'},
    {key: 'FACTORY', value: 'Завод'},
    {key: 'SCHOOL', value: 'Учебное учреждение'},
    {key: 'MBASE', value: 'Воинская часть'},
    {key: 'LHOUSE', value: 'Маяк'},
    {key: 'ESTATE', value: 'Усадьба'},
    {key: 'BTOWER', value: 'Башня Бисмарка'},
    {key: 'BASTION', value: 'Бастион'},
    {key: 'GATE', value: 'Ворота'},
    {key: 'FORT', value: 'Форт'},
    {key: 'MILITARY', value: 'Военный объект'},
    {key: 'PMEMORIAL', value: 'Памятник'},
    {key: 'VILLA', value: 'Вилла'},
    {key: 'TECH', value: 'Техническое сооружение'},
    {key: 'PALACE', value: 'Дворец'},
    {key: 'BRIDGE', value: 'Мост'},
    {key: 'FWERK', value: 'Фахверк'},
    {key: 'HOSPITAL', value: 'Лечебное учреждение'},
    {key: 'TSTATION', value: 'Вокзал'},
    {key: 'FIREDEPT', value: 'Пожарная часть'},
    {key: 'MILL', value: 'Мельница'},
    {key: 'POSTAMT', value: 'Почтамт'},
    {key: 'POLICE', value: 'Полиция'},
    {key: 'STORAGE', value: 'Склад'},
    {key: 'HOTEL', value: 'Отель'},
    {key: 'MOSAIC', value: 'Мозаика'},
    {key: 'FOUNTAIN', value: 'Фонтан'},
    {key: 'SCULPTURE', value: 'Скульптура'},
    {key: 'BUNKER', value: 'Бункер'},
    {key: 'HANGAR', value: 'Ангар'},
    {key: 'DOT', value: 'Дот'},
    {key: 'SHELTER', value: 'Убежище'},
    {key: 'ETOWER', value: 'Башня трансформатораная'},
    {key: 'MINOR', value: 'Малые архитектурные формы'},
    {key: 'TWTOWER', value: 'Башня водонапорная железнодорожная'},
    {key: 'WTECH', value: 'Гидротехническое сооружение'},
    {key: 'BARN', value: 'Амбар'},
    {key: 'PRISON', value: 'Тюрьма'},
    {key: 'HYDRANT', value: 'Гидрант'},
    {key: 'HATCH', value: 'Люк'},
    {key: 'STONE', value: 'Камень'},
    {key: 'USSR', value: 'СССР'},
]);
