import Enum from '../../../lib/base/enum/index.js';

export default new Enum([
    {value: 'Foreign Crimson', key: 'FOREIGN_CRIMSON', keyLess: 'foreign-crimson', hex: 'c91f37'},
    {value: 'Red Orange', key: 'RED_ORANGE', keyLess: 'red-orange', hex: 'dc3023'},
    {value: 'Cochineal Red', key: 'COCHINEAL_RED', keyLess: 'cochineal-red', hex: '9d2933'},
    {value: 'Monza', key: 'MONZA', keyLess: 'monza', hex: 'cf000f'},
    {value: 'Brewed Mustard-brown', key: 'BREWED_MUSTARD_BROWN', keyLess: 'brewed-mustard-brown', hex: 'e68364'},
    {value: 'Pomegranate', key: 'POMEGRANATE', keyLess: 'pomegranate', hex: 'f22613'},
    {value: 'Scarlet', key: 'SCARLET', keyLess: 'scarlet', hex: 'cf3a24'},
    {value: 'Pure Crimson', key: 'PURE_CRIMSON', keyLess: 'pure-crimson', hex: 'c3272b'},
    {value: 'True Red', key: 'TRUE_RED', keyLess: 'true-red', hex: '8f1d21'},
    {value: 'Chestnut Rose', key: 'CHESTNUT_ROSE', keyLess: 'chestnut-rose', hex: 'd24d57'},
    {value: 'One Kin Dye', key: 'ONE_KIN_DYE', keyLess: 'one-kin-dye', hex: 'f08f90'},
    {value: 'Peach-colored', key: 'PEACH_COLORED', keyLess: 'peach-colored', hex: 'f47983'},
    {value: 'Red Plum Colored', key: 'RED_PLUM_COLORED', keyLess: 'red-plum-colored', hex: 'db5a6b'},
    {value: 'Medium Crimson', key: 'MEDIUM_CRIMSON', keyLess: 'medium-crimson', hex: 'c93756'},
    {value: 'Cherry Blossom Color', key: 'CHERRY_BLOSSOM_COLOR', keyLess: 'cherry-blossom-color', hex: 'fcc9b9'},
    {value: 'Washed-out Crimson', key: 'WASHED_OUT_CRIMSON', keyLess: 'washed-out-crimson', hex: 'ffb3a7'},
    {value: 'Radical Red', key: 'RADICAL_RED', keyLess: 'radical-red', hex: 'f62459'},
    {value: 'Ibis Wing Color', key: 'IBIS_WING_COLOR', keyLess: 'ibis-wing-color', hex: 'f58f84'},
    {value: 'Wisteria Purple', key: 'WISTERIA_PURPLE', keyLess: 'wisteria-purple', hex: '875f9a'},
    {value: 'Bellflower Color', key: 'BELLFLOWER_COLOR', keyLess: 'bellflower-color', hex: '5d3f6a'},
    {value: 'Wisteria Color', key: 'WISTERIA_COLOR', keyLess: 'wisteria-color', hex: '89729e'},
    {value: 'Iris Color', key: 'IRIS_COLOR', keyLess: 'iris-color', hex: '763568'},
    {value: 'Tatarian Aster Color', key: 'TATARIAN_ASTER_COLOR', keyLess: 'tatarian-aster-color', hex: '8d608c'},
    {value: 'Thin Color', key: 'THIN_COLOR', keyLess: 'thin-color', hex: 'a87ca0'},
    {value: 'Violet Color', key: 'VIOLET_COLOR', keyLess: 'violet-color', hex: '5b3256'},
    {value: 'Medium Purple', key: 'MEDIUM_PURPLE', keyLess: 'medium-purple', hex: 'bf55ec'},
    {value: 'Studio', key: 'STUDIO', keyLess: 'studio', hex: '8e44ad'},
    {value: 'Wisteria', key: 'WISTERIA', keyLess: 'wisteria', hex: '9b59b6'},
    {value: 'Light Wisteria', key: 'LIGHT_WISTERIA', keyLess: 'light-wisteria', hex: 'be90d4'},
    {value: 'Sky Color', key: 'SKY_COLOR', keyLess: 'sky-color', hex: '4d8fac'},
    {value: 'Ultramarine Color', key: 'ULTRAMARINE_COLOR', keyLess: 'ultramarine-color', hex: '5d8cae'},
    {value: 'Picton Blue', key: 'PICTON_BLUE', keyLess: 'picton-blue', hex: '22a7f0'},
    {value: 'Dodger Blue', key: 'DODGER_BLUE', keyLess: 'dodger-blue', hex: '19b5fe'},
    {value: 'Picton Blue 2', key: 'PICTON_BLUE_2', keyLess: 'picton-blue-2', hex: '59abe3'},
    {value: 'Light Blue Color', key: 'LIGHT_BLUE_COLOR', keyLess: 'light-blue-color', hex: '48929b'},
    {value: 'Thousand Herb', key: 'THOUSAND_HERB', keyLess: 'thousand-herb', hex: '317589'},
    {value: 'Jordy Blue', key: 'JORDY_BLUE', keyLess: 'jordy-blue', hex: '89c4f4'},
    {value: 'Steel Blue', key: 'STEEL_BLUE', keyLess: 'steel-blue', hex: '4b77be'},
    {value: 'Lapis Lazuli Color', key: 'LAPIS_LAZULI_COLOR', keyLess: 'lapis-lazuli-color', hex: '1f4788'},
    {value: 'Navy Blue Color', key: 'NAVY_BLUE_COLOR', keyLess: 'navy-blue-color', hex: '003171'},
    {value: 'Hanada', key: 'HANADA', keyLess: 'hanada', hex: '044f67'},
    {value: 'Indigo Color', key: 'INDIGO_COLOR', keyLess: 'indigo-color', hex: '264348'},
    {value: 'Siskin Sprout Yellow', key: 'SISKIN_SPROUT_YELLOW', keyLess: 'siskin-sprout-yellow', hex: '7a942e'},
    {value: 'Young Green Onion', key: 'YOUNG_GREEN_ONION', keyLess: 'young-green-onion', hex: '8db255'},
    {value: 'Fresh Onion', key: 'FRESH_ONION', keyLess: 'fresh-onion', hex: '5b8930'},
    {value: 'Young Bamboo Color', key: 'YOUNG_BAMBOO_COLOR', keyLess: 'young-bamboo-color', hex: '6b9362'},
    {value: 'Patina', key: 'PATINA', keyLess: 'patina', hex: '407a52'},
    {value: 'Green Bamboo', key: 'GREEN_BAMBOO', keyLess: 'green-bamboo', hex: '006442'},
    {value: 'Gossip', key: 'GOSSIP', keyLess: 'gossip', hex: '87d37c'},
    {value: 'Eucalyptus', key: 'EUCALYPTUS', keyLess: 'eucalyptus', hex: '26a65b'},
    {value: 'Jungle Green', key: 'JUNGLE_GREEN', keyLess: 'jungle-green', hex: '26c281'},
    {value: 'Observatory', key: 'OBSERVATORY', keyLess: 'observatory', hex: '049372'},
    {value: 'Jungle Green 2', key: 'JUNGLE_GREEN_2', keyLess: 'jungle-green-2', hex: '2abb9b'},
    {value: 'Mountain Meadow', key: 'MOUNTAIN_MEADOW', keyLess: 'mountain-meadow', hex: '16a085'},
    {value: 'Turquoise', key: 'TURQUOISE', keyLess: 'turquoise', hex: '36d7b7'},
    {value: 'Free Speech Aquamarine', key: 'FREE_SPEECH_AQUAMARINE', keyLess: 'free-speech-aquamarine', hex: '03a678'},
    {value: 'Ocean Green', key: 'OCEAN_GREEN', keyLess: 'ocean-green', hex: '4daf7c'},
    {value: 'Patrinia Flowers', key: 'PATRINIA_FLOWERS', keyLess: 'patrinia-flowers', hex: 'd9b611'},
    {value: 'Amur Cork Tree', key: 'AMUR_CORK_TREE', keyLess: 'amur-cork-tree', hex: 'f3c13a'},
    {value: 'Ripe Lemon', key: 'RIPE_LEMON', keyLess: 'ripe-lemon', hex: 'f7ca18'},
    {value: 'Japanese Triandra Grass', key: 'JAPANESE_TRIANDRA_GRASS', keyLess: 'japanese-triandra-grass', hex: 'e2b13c'},
    {value: 'Rapeseed Oil-colored', key: 'RAPESEED_OIL_COLORED', keyLess: 'rapeseed-oil-colored', hex: 'a17917'},
    {value: 'Cream Can', key: 'CREAM_CAN', keyLess: 'cream-can', hex: 'f5d76e'},
    {value: 'Saffron', key: 'SAFFRON', keyLess: 'saffron', hex: 'f4d03f'},
    {value: 'Bright Golden Yellow', key: 'BRIGHT_GOLDEN_YELLOW', keyLess: 'bright-golden-yellow', hex: 'ffa400'},
    {value: 'Sumac-dyed', key: 'SUMAC_DYED', keyLess: 'sumac-dyed', hex: 'e08a1e'},
    {value: 'Gamboge', key: 'GAMBOGE', keyLess: 'gamboge', hex: 'ffb61e'},
    {value: 'Corn-colored', key: 'CORN_COLORED', keyLess: 'corn-colored', hex: 'faa945'},
    {value: 'Egg-colored', key: 'EGG_COLORED', keyLess: 'egg-colored', hex: 'ffa631'},
    {value: 'Floral Leaf-colored', key: 'FLORAL_LEAF_COLORED', keyLess: 'floral-leaf-colored', hex: 'ffb94e'},
    {value: 'Golden Fallen Leaves', key: 'GOLDEN_FALLEN_LEAVES', keyLess: 'golden-fallen-leaves', hex: 'e29c45'},
    {value: 'Ecstasy', key: 'ECSTASY', keyLess: 'ecstasy', hex: 'f9690e'},
    {value: 'Amber', key: 'AMBER', keyLess: 'amber', hex: 'ca6924'},
    {value: 'Lightning Yellow', key: 'LIGHTNING_YELLOW', keyLess: 'lightning-yellow', hex: 'f5ab35'},
    {value: 'Silver', key: 'SILVER', keyLess: 'silver', hex: 'bfbfbf'},
    {value: 'Cararra', key: 'CARARRA', keyLess: 'cararra', hex: 'f2f1ef'},
    {value: 'Silver Sand', key: 'SILVER_SAND', keyLess: 'silver-sand', hex: 'bdc3c7'},
    {value: 'Porcelain', key: 'PORCELAIN', keyLess: 'porcelain', hex: 'ecf0f1'},
    {value: 'Pumice', key: 'PUMICE', keyLess: 'pumice', hex: 'd2d7d3'},
    {value: 'Harbor Rat', key: 'HARBOR_RAT', keyLess: 'harbor-rat', hex: '757d75'},
    {value: 'Gallery', key: 'GALLERY', keyLess: 'gallery', hex: 'eeeeee'},
    {value: 'Edward', key: 'EDWARD', keyLess: 'edward', hex: 'abb7b7'},
    {value: 'Lynch', key: 'LYNCH', keyLess: 'lynch', hex: '6c7a89'},
    {value: 'Cascade', key: 'CASCADE', keyLess: 'cascade', hex: '95a5a6'},

]);
