version: '3'

services:

  legacy.devel.images:
    image: "awesome1888/image-server:latest"
    ports:
      - 3200:3200
    volumes:
      - "/home/vagrant/volume-development/upload/:/usr/src/app/volume/upload/"
    restart: on-failure
    environment:
      - PORT=3200
      - ROOT_URL=http://localhost
      - NODE_ENV=production
      - STORAGE_PATH=/usr/src/app/volume/upload/
      - CACHE_PATH=/usr/src/app/.resize-cache/
  legacy.devel.db:
      image: "mongo:3.6"
      restart: on-failure
      ports:
        - "3300:27017"
  legacy.devel.db.backuper:
      image: "awesome1888/db-backuper:latest"
      restart: on-failure
      volumes:
        - "/home/vagrant/volume-development/db/:/usr/src/app/volume/"
      environment:
        - NODE_ENV=production
        - STORAGE_PATH=/usr/src/app/volume/
        - MONGO_URL=mongodb://legacy.devel.db:27017/legacy
        - DO_DAILY=1
        - DO_MONTHLY=1
  legacy.devel.portainer:
      image: portainer/portainer
      ports:
        - "3900:9000"
      command: -H unix:///var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

volumes:
  portainer_data:

