name: CD.prussiascan-api.runAPI

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
#          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
#          REQUIREMENTS: folder/requirements.txt
